const data = [
  {
    'Book Id': 22313627,
    Title: 'Words of Radiance (The Stormlight Archive, #2)',
    Author: 'Brandon Sanderson',
    'Author l-f': 'Sanderson, Brandon',
    'Additional Authors': '',
    ISBN: '0765365286',
    ISBN13: 9780765365286,
    'My Rating': 4,
    'Average Rating': 4.75,
    Publisher: 'Tor Fantasy',
    Binding: 'Mass Market Paperback',
    'Number of Pages': 1310,
    'Year Published': 2015,
    'Original Publication Year': 2014,
    'Date Read': '2022/03/23',
    'Date Added': '2021/12/22',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 642049,
    Title: 'Hunters Of Dune (Dune Chronicles, #7)',
    Author: 'Brian Herbert',
    'Author l-f': 'Herbert, Brian',
    'Additional Authors': 'Kevin J. Anderson',
    ISBN: '076535148X',
    ISBN13: 9780765351487,
    'My Rating': 4,
    'Average Rating': 3.66,
    Publisher: 'Tor Science Fiction',
    Binding: 'Mass Market Paperback',
    'Number of Pages': 576,
    'Year Published': 2007,
    'Original Publication Year': 2006,
    'Date Read': '2013/03/10',
    'Date Added': '2013/02/14',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 40701780,
    Title: 'The Wisdom of Crowds (The Age of Madness, #3)',
    Author: 'Joe Abercrombie',
    'Author l-f': 'Abercrombie, Joe',
    'Additional Authors': '',
    ISBN: '0575095970',
    ISBN13: 9780575095977,
    'My Rating': 5,
    'Average Rating': 4.61,
    Publisher: 'Gollancz',
    Binding: 'Paperback',
    'Number of Pages': 520,
    'Year Published': 2021,
    'Original Publication Year': 2021,
    'Date Read': '2021/10/11',
    'Date Added': '2021/09/17',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 44767458,
    Title: 'Dune (Dune, #1)',
    Author: 'Frank Herbert',
    'Author l-f': 'Herbert, Frank',
    'Additional Authors': '',
    ISBN: '059309932X',
    ISBN13: 9780593099322,
    'My Rating': 5,
    'Average Rating': 4.25,
    Publisher: 'Ace Books',
    Binding: 'Hardcover',
    'Number of Pages': 658,
    'Year Published': 2019,
    'Original Publication Year': 1965,
    'Date Read': '',
    'Date Added': '2021/09/17',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 488555,
    Title:
      'Star Wars, Episode III: Revenge of the Sith (Star Wars: Novelizations #3)',
    Author: 'Matthew Woodring Stover',
    'Author l-f': 'Stover, Matthew Woodring',
    'Additional Authors': 'George Lucas',
    ISBN: '0345428846',
    ISBN13: 9780345428844,
    'My Rating': 5,
    'Average Rating': 4.19,
    Publisher: 'Del Rey/Ballantine Books',
    Binding: 'Mass Market Paperback',
    'Number of Pages': 451,
    'Year Published': 2005,
    'Original Publication Year': 2005,
    'Date Read': '2021/02/28',
    'Date Added': '2021/02/16',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 11085563,
    Title:
      'The Effortless Sleep Method: The Incredible New Cure for Insomnia and Chronic Sleep Problems',
    Author: 'Sasha Stephens',
    'Author l-f': 'Stephens, Sasha',
    'Additional Authors': '',
    ISBN: '1456492543',
    ISBN13: 9781456492540,
    'My Rating': 5,
    'Average Rating': 3.76,
    Publisher: 'Createspace Independent Publishing Platform',
    Binding: 'Paperback',
    'Number of Pages': 186,
    'Year Published': 2011,
    'Original Publication Year': 2011,
    'Date Read': '',
    'Date Added': '2021/02/25',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 504420,
    Title: 'Protect and Defend (Mitch Rapp, #10)',
    Author: 'Vince Flynn',
    'Author l-f': 'Flynn, Vince',
    'Additional Authors': '',
    ISBN: '074327041X',
    ISBN13: 9780743270410,
    'My Rating': 4,
    'Average Rating': 4.34,
    Publisher: 'Atria Books',
    Binding: 'Hardcover',
    'Number of Pages': 416,
    'Year Published': 2007,
    'Original Publication Year': 2007,
    'Date Read': '2020/12/30',
    'Date Added': '2020/12/16',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 67035,
    Title: 'Relic (Pendergast, #1)',
    Author: 'Douglas Preston',
    'Author l-f': 'Preston, Douglas',
    'Additional Authors': 'Lincoln Child',
    ISBN: '0765354942',
    ISBN13: 9780765354945,
    'My Rating': 4,
    'Average Rating': 4.04,
    Publisher: 'Tor Books',
    Binding: 'Paperback',
    'Number of Pages': 480,
    'Year Published': 2005,
    'Original Publication Year': 1995,
    'Date Read': '2020/09/27',
    'Date Added': '2020/09/01',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 755023,
    Title: 'Shadow and Claw (The Book of the New Sun, #1-2)',
    Author: 'Gene Wolfe',
    'Author l-f': 'Wolfe, Gene',
    'Additional Authors': '',
    ISBN: '1857989775',
    ISBN13: 9781857989779,
    'My Rating': 2,
    'Average Rating': 4.02,
    Publisher: 'Victor Gollancz',
    Binding: 'Paperback',
    'Number of Pages': 608,
    'Year Published': 2000,
    'Original Publication Year': 1994,
    'Date Read': '2020/08/13',
    'Date Added': '2020/07/18',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 28335696,
    Title: 'Persepolis Rising (The Expanse, #7)',
    Author: 'James S.A. Corey',
    'Author l-f': 'Corey, James S.A.',
    'Additional Authors': '',
    ISBN: '0316332828',
    ISBN13: 9780316332828,
    'My Rating': 4,
    'Average Rating': 4.37,
    Publisher: 'Orbit Books',
    Binding: 'ebook',
    'Number of Pages': 608,
    'Year Published': 2017,
    'Original Publication Year': 2017,
    'Date Read': '2020/07/18',
    'Date Added': '2020/06/13',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 27914988,
    Title: "The Dark Forest (Remembrance of Earth's Past, #2)",
    Author: 'Liu Cixin',
    'Author l-f': 'Cixin, Liu',
    'Additional Authors': 'Joel Martinson',
    ISBN: '1784971618',
    ISBN13: 9781784971618,
    'My Rating': 4,
    'Average Rating': 4.41,
    Publisher: 'Head of Zeus ',
    Binding: 'Paperback',
    'Number of Pages': 550,
    'Year Published': 2016,
    'Original Publication Year': 2008,
    'Date Read': '2020/04/15',
    'Date Added': '2020/04/08',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 20174424,
    Title: 'City of Stairs (The Divine Cities, #1)',
    Author: 'Robert Jackson Bennett',
    'Author l-f': 'Bennett, Robert Jackson',
    'Additional Authors': '',
    ISBN: '080413717X',
    ISBN13: 9780804137171,
    'My Rating': 5,
    'Average Rating': 4.08,
    Publisher: 'Broadway Books',
    Binding: 'Paperback',
    'Number of Pages': 452,
    'Year Published': 2014,
    'Original Publication Year': 2014,
    'Date Read': '2020/03/28',
    'Date Added': '2020/03/01',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 42523459,
    Title: 'Thirteen',
    Author: 'Richard K. Morgan',
    'Author l-f': 'Morgan, Richard K.',
    'Additional Authors': '',
    ISBN: '1473225388',
    ISBN13: 9781473225381,
    'My Rating': 4,
    'Average Rating': 3.9,
    Publisher: 'Gollancz',
    Binding: 'Paperback',
    'Number of Pages': 630,
    'Year Published': 2018,
    'Original Publication Year': 2007,
    'Date Read': '2020/02/06',
    'Date Added': '2020/01/15',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
];

export default data;
