const exportedData = [
  {
    'Book Id': 22313627,
    Title: 'Words of Radiance (The Stormlight Archive, #2)',
    Author: 'Brandon Sanderson',
    'Author l-f': 'Sanderson, Brandon',
    'Additional Authors': '',
    ISBN: '0765365286',
    ISBN13: 9780765365286,
    'My Rating': 4,
    'Average Rating': 4.75,
    Publisher: 'Tor Fantasy',
    Binding: 'Mass Market Paperback',
    'Number of Pages': 1310,
    'Year Published': 2015,
    'Original Publication Year': 2014,
    'Date Read': '2022/03/23',
    'Date Added': '2021/12/22',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 642049,
    Title: 'Hunters Of Dune (Dune Chronicles, #7)',
    Author: 'Brian Herbert',
    'Author l-f': 'Herbert, Brian',
    'Additional Authors': 'Kevin J. Anderson',
    ISBN: '076535148X',
    ISBN13: 9780765351487,
    'My Rating': 4,
    'Average Rating': 3.66,
    Publisher: 'Tor Science Fiction',
    Binding: 'Mass Market Paperback',
    'Number of Pages': 576,
    'Year Published': 2007,
    'Original Publication Year': 2006,
    'Date Read': '2013/03/10',
    'Date Added': '2013/02/14',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 40701780,
    Title: 'The Wisdom of Crowds (The Age of Madness, #3)',
    Author: 'Joe Abercrombie',
    'Author l-f': 'Abercrombie, Joe',
    'Additional Authors': '',
    ISBN: '0575095970',
    ISBN13: 9780575095977,
    'My Rating': 5,
    'Average Rating': 4.61,
    Publisher: 'Gollancz',
    Binding: 'Paperback',
    'Number of Pages': 520,
    'Year Published': 2021,
    'Original Publication Year': 2021,
    'Date Read': '2021/10/11',
    'Date Added': '2021/09/17',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 44767458,
    Title: 'Dune (Dune, #1)',
    Author: 'Frank Herbert',
    'Author l-f': 'Herbert, Frank',
    'Additional Authors': '',
    ISBN: '059309932X',
    ISBN13: 9780593099322,
    'My Rating': 5,
    'Average Rating': 4.25,
    Publisher: 'Ace Books',
    Binding: 'Hardcover',
    'Number of Pages': 658,
    'Year Published': 2019,
    'Original Publication Year': 1965,
    'Date Read': '',
    'Date Added': '2021/09/17',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 488555,
    Title:
      'Star Wars, Episode III: Revenge of the Sith (Star Wars: Novelizations #3)',
    Author: 'Matthew Woodring Stover',
    'Author l-f': 'Stover, Matthew Woodring',
    'Additional Authors': 'George Lucas',
    ISBN: '0345428846',
    ISBN13: 9780345428844,
    'My Rating': 5,
    'Average Rating': 4.19,
    Publisher: 'Del Rey/Ballantine Books',
    Binding: 'Mass Market Paperback',
    'Number of Pages': 451,
    'Year Published': 2005,
    'Original Publication Year': 2005,
    'Date Read': '2021/02/28',
    'Date Added': '2021/02/16',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 11085563,
    Title:
      'The Effortless Sleep Method: The Incredible New Cure for Insomnia and Chronic Sleep Problems',
    Author: 'Sasha Stephens',
    'Author l-f': 'Stephens, Sasha',
    'Additional Authors': '',
    ISBN: '1456492543',
    ISBN13: 9781456492540,
    'My Rating': 5,
    'Average Rating': 3.76,
    Publisher: 'Createspace Independent Publishing Platform',
    Binding: 'Paperback',
    'Number of Pages': 186,
    'Year Published': 2011,
    'Original Publication Year': 2011,
    'Date Read': '',
    'Date Added': '2021/02/25',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 504420,
    Title: 'Protect and Defend (Mitch Rapp, #10)',
    Author: 'Vince Flynn',
    'Author l-f': 'Flynn, Vince',
    'Additional Authors': '',
    ISBN: '074327041X',
    ISBN13: 9780743270410,
    'My Rating': 4,
    'Average Rating': 4.34,
    Publisher: 'Atria Books',
    Binding: 'Hardcover',
    'Number of Pages': 416,
    'Year Published': 2007,
    'Original Publication Year': 2007,
    'Date Read': '2020/12/30',
    'Date Added': '2020/12/16',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 40701777,
    Title: 'The Trouble with Peace (The Age of Madness, #2)',
    Author: 'Joe Abercrombie',
    'Author l-f': 'Abercrombie, Joe',
    'Additional Authors': '',
    ISBN: '0575095911',
    ISBN13: 9780575095915,
    'My Rating': 5,
    'Average Rating': 4.61,
    Publisher: 'Gollancz',
    Binding: 'Hardcover',
    'Number of Pages': 506,
    'Year Published': 2020,
    'Original Publication Year': 2020,
    'Date Read': '2020/10/27',
    'Date Added': '2020/09/27',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review':
      "And once  again -  a superb book. Story maybe a bit sluggish at the beginning but then gets full-steam in the last quarter so its just hard to put down. The characters are all  vivid and bright, the plot twists were  really hard to predict. This is barely a fantasy novel anymore but  rather a tell of realpolitik and war only set into an imaginary world. And of course famous one-liners and witty humour are all in place.  Five out of five, Joe Abercrombie as usual surpasses every expectation.Just can't wait yet another year for the wrap up.",
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 67035,
    Title: 'Relic (Pendergast, #1)',
    Author: 'Douglas Preston',
    'Author l-f': 'Preston, Douglas',
    'Additional Authors': 'Lincoln Child',
    ISBN: '0765354942',
    ISBN13: 9780765354945,
    'My Rating': 4,
    'Average Rating': 4.04,
    Publisher: 'Tor Books',
    Binding: 'Paperback',
    'Number of Pages': 480,
    'Year Published': 2005,
    'Original Publication Year': 1995,
    'Date Read': '2020/09/27',
    'Date Added': '2020/09/01',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 755023,
    Title: 'Shadow and Claw (The Book of the New Sun, #1-2)',
    Author: 'Gene Wolfe',
    'Author l-f': 'Wolfe, Gene',
    'Additional Authors': '',
    ISBN: '1857989775',
    ISBN13: 9781857989779,
    'My Rating': 5,
    'Average Rating': 4.02,
    Publisher: 'Victor Gollancz',
    Binding: 'Paperback',
    'Number of Pages': 608,
    'Year Published': 2000,
    'Original Publication Year': 1994,
    'Date Read': '2020/08/13',
    'Date Added': '2020/07/18',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 28335696,
    Title: 'Persepolis Rising (The Expanse, #7)',
    Author: 'James S.A. Corey',
    'Author l-f': 'Corey, James S.A.',
    'Additional Authors': '',
    ISBN: '0316332828',
    ISBN13: 9780316332828,
    'My Rating': 4,
    'Average Rating': 4.37,
    Publisher: 'Orbit Books',
    Binding: 'ebook',
    'Number of Pages': 608,
    'Year Published': 2017,
    'Original Publication Year': 2017,
    'Date Read': '2020/07/18',
    'Date Added': '2020/06/13',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 27914988,
    Title: "The Dark Forest (Remembrance of Earth's Past, #2)",
    Author: 'Liu Cixin',
    'Author l-f': 'Cixin, Liu',
    'Additional Authors': 'Joel Martinson',
    ISBN: '1784971618',
    ISBN13: 9781784971618,
    'My Rating': 4,
    'Average Rating': 4.41,
    Publisher: 'Head of Zeus ',
    Binding: 'Paperback',
    'Number of Pages': 550,
    'Year Published': 2016,
    'Original Publication Year': 2008,
    'Date Read': '2020/04/15',
    'Date Added': '2020/04/08',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 20174424,
    Title: 'City of Stairs (The Divine Cities, #1)',
    Author: 'Robert Jackson Bennett',
    'Author l-f': 'Bennett, Robert Jackson',
    'Additional Authors': '',
    ISBN: '080413717X',
    ISBN13: 9780804137171,
    'My Rating': 5,
    'Average Rating': 4.08,
    Publisher: 'Broadway Books',
    Binding: 'Paperback',
    'Number of Pages': 452,
    'Year Published': 2014,
    'Original Publication Year': 2014,
    'Date Read': '2020/03/28',
    'Date Added': '2020/03/01',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 42523459,
    Title: 'Thirteen',
    Author: 'Richard K. Morgan',
    'Author l-f': 'Morgan, Richard K.',
    'Additional Authors': '',
    ISBN: '1473225388',
    ISBN13: 9781473225381,
    'My Rating': 4,
    'Average Rating': 3.9,
    Publisher: 'Gollancz',
    Binding: 'Paperback',
    'Number of Pages': 630,
    'Year Published': 2018,
    'Original Publication Year': 2007,
    'Date Read': '2020/02/06',
    'Date Added': '2020/01/15',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 18505802,
    Title:
      'Console Wars: Sega, Nintendo, and the Battle that Defined a Generation',
    Author: 'Blake J. Harris',
    'Author l-f': 'Harris, Blake J.',
    'Additional Authors': '',
    ISBN: '0062276697',
    ISBN13: 9780062276698,
    'My Rating': 4,
    'Average Rating': 3.95,
    Publisher: 'It Books',
    Binding: 'Hardcover',
    'Number of Pages': 576,
    'Year Published': 2014,
    'Original Publication Year': 2014,
    'Date Read': '2019/11/09',
    'Date Added': '2019/10/22',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 44350875,
    Title: 'A Little Hatred (The Age of Madness, #1)',
    Author: 'Joe Abercrombie',
    'Author l-f': 'Abercrombie, Joe',
    'Additional Authors': '',
    ISBN: '0575095865',
    ISBN13: 9780575095861,
    'My Rating': 5,
    'Average Rating': 4.45,
    Publisher: 'Gollancz',
    Binding: 'Hardcover',
    'Number of Pages': 471,
    'Year Published': 2019,
    'Original Publication Year': 2019,
    'Date Read': '2019/10/06',
    'Date Added': '2019/09/28',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review':
      "Fabulous. Joe Abercrombie at its finest. Read the second half of the book in just ONE DAY - and even though  English is not my native language. Some plot twists were amazing. This is how modern fantasy should be written. Just can't wait to read the next book!!",
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 20518872,
    Title: 'The Three-Body Problem (Remembrance of Earth’s Past #1)',
    Author: 'Liu Cixin',
    'Author l-f': 'Cixin, Liu',
    'Additional Authors': 'Ken Liu',
    ISBN: '0765377063',
    ISBN13: 9780765377067,
    'My Rating': 5,
    'Average Rating': 4.07,
    Publisher: 'Tor Books',
    Binding: 'Hardcover',
    'Number of Pages': 399,
    'Year Published': 2014,
    'Original Publication Year': 2006,
    'Date Read': '2019/08/28',
    'Date Added': '2019/08/19',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 154424,
    Title: 'Consent to Kill (Mitch Rapp, #8)',
    Author: 'Vince Flynn',
    'Author l-f': 'Flynn, Vince',
    'Additional Authors': '',
    ISBN: '1416505016',
    ISBN13: 9781416505013,
    'My Rating': 5,
    'Average Rating': 4.38,
    Publisher: 'Pocket Star',
    Binding: 'Paperback',
    'Number of Pages': 675,
    'Year Published': 2006,
    'Original Publication Year': 2005,
    'Date Read': '2019/08/19',
    'Date Added': '2019/08/05',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 26030742,
    Title: 'Sharp Ends (First Law World, #7)',
    Author: 'Joe Abercrombie',
    'Author l-f': 'Abercrombie, Joe',
    'Additional Authors': '',
    ISBN: '031639081X',
    ISBN13: 9780316390811,
    'My Rating': 5,
    'Average Rating': 4.15,
    Publisher: 'Orbit',
    Binding: 'Hardcover',
    'Number of Pages': 304,
    'Year Published': 2016,
    'Original Publication Year': 2016,
    'Date Read': '2019/08/05',
    'Date Added': '2019/07/21',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 6072318,
    Title: 'The Winds of Dune (Heroes of Dune #2)',
    Author: 'Brian Herbert',
    'Author l-f': 'Herbert, Brian',
    'Additional Authors': 'Kevin J. Anderson',
    ISBN: '0765322722',
    ISBN13: 9780765322722,
    'My Rating': 4,
    'Average Rating': 3.79,
    Publisher: 'Tor Books',
    Binding: 'Hardcover',
    'Number of Pages': 448,
    'Year Published': 2009,
    'Original Publication Year': 2009,
    'Date Read': '2019/07/21',
    'Date Added': '2019/06/29',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 25877663,
    Title: "Babylon's Ashes (The Expanse, #6)",
    Author: 'James S.A. Corey',
    'Author l-f': 'Corey, James S.A.',
    'Additional Authors': '',
    ISBN: '0356504263',
    ISBN13: 9780356504261,
    'My Rating': 3,
    'Average Rating': 4.23,
    Publisher: 'Orbit',
    Binding: 'Hardcover',
    'Number of Pages': 538,
    'Year Published': 2016,
    'Original Publication Year': 2016,
    'Date Read': '2019/06/16',
    'Date Added': '2019/05/21',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 184657,
    Title: 'Memorial Day (Mitch Rapp, #7)',
    Author: 'Vince Flynn',
    'Author l-f': 'Flynn, Vince',
    'Additional Authors': '',
    ISBN: '1416548009',
    ISBN13: 9781416548003,
    'My Rating': 4,
    'Average Rating': 4.31,
    Publisher: 'Pocket Books',
    Binding: 'Paperback',
    'Number of Pages': 574,
    'Year Published': 2007,
    'Original Publication Year': 2004,
    'Date Read': '2019/05/21',
    'Date Added': '2019/04/21',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 13521459,
    Title: 'Red Country (First Law World, #6)',
    Author: 'Joe Abercrombie',
    'Author l-f': 'Abercrombie, Joe',
    'Additional Authors': '',
    ISBN: '0316214442',
    ISBN13: 9780316214445,
    'My Rating': 5,
    'Average Rating': 4.31,
    Publisher: 'Orbit',
    Binding: 'ebook',
    'Number of Pages': 469,
    'Year Published': 2012,
    'Original Publication Year': 2012,
    'Date Read': '2019/04/20',
    'Date Added': '2019/03/27',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': 'An epic stroke for the brilliantly written series!',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 36595101,
    Title: 'Fire and Fury: Inside the Trump White House',
    Author: 'Michael Wolff',
    'Author l-f': 'Wolff, Michael',
    'Additional Authors': '',
    ISBN: '1250158060',
    ISBN13: 9781250158062,
    'My Rating': 3,
    'Average Rating': 3.44,
    Publisher: 'Henry Holt & Company',
    Binding: 'Hardcover',
    'Number of Pages': 322,
    'Year Published': 2018,
    'Original Publication Year': 2018,
    'Date Read': '2019/03/27',
    'Date Added': '2019/03/10',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 28962996,
    Title: 'Six Wakes',
    Author: 'Mur Lafferty',
    'Author l-f': 'Lafferty, Mur',
    'Additional Authors': '',
    ISBN: '0316389684',
    ISBN13: 9780316389686,
    'My Rating': 4,
    'Average Rating': 3.83,
    Publisher: 'Orbit',
    Binding: 'Paperback',
    'Number of Pages': 364,
    'Year Published': 2017,
    'Original Publication Year': 2017,
    'Date Read': '2019/03/10',
    'Date Added': '2019/02/27',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 830502,
    Title: 'It',
    Author: 'Stephen King',
    'Author l-f': 'King, Stephen',
    'Additional Authors': '',
    ISBN: '0450411435',
    ISBN13: 9780450411434,
    'My Rating': 5,
    'Average Rating': 4.25,
    Publisher: 'New English Library',
    Binding: 'Paperback',
    'Number of Pages': 1116,
    'Year Published': 1987,
    'Original Publication Year': 1986,
    'Date Read': '2019/02/27',
    'Date Added': '2019/01/24',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 2920001,
    Title: 'Paul of Dune (Heroes of Dune #1)',
    Author: 'Brian Herbert',
    'Author l-f': 'Herbert, Brian',
    'Additional Authors': 'Kevin J. Anderson',
    ISBN: '0765312948',
    ISBN13: 9780765312945,
    'My Rating': 4,
    'Average Rating': 3.72,
    Publisher: 'Tor Books',
    Binding: 'Hardcover',
    'Number of Pages': 512,
    'Year Published': 2008,
    'Original Publication Year': 2008,
    'Date Read': '2019/01/24',
    'Date Added': '2019/01/06',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 624023,
    Title: 'Parasite Eve',
    Author: 'Hideaki Sena',
    'Author l-f': 'Sena, Hideaki',
    'Additional Authors': 'Tyran Grillo',
    ISBN: '1932234195',
    ISBN13: 9781932234190,
    'My Rating': 0,
    'Average Rating': 3.6,
    Publisher: 'Vertical',
    Binding: 'Hardcover',
    'Number of Pages': 320,
    'Year Published': 2005,
    'Original Publication Year': 1994,
    'Date Read': '',
    'Date Added': '2018/12/30',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 777211,
    Title: 'Executive Power (Mitch Rapp, #6)',
    Author: 'Vince Flynn',
    'Author l-f': 'Flynn, Vince',
    'Additional Authors': '',
    ISBN: '0743453964',
    ISBN13: 9780743453967,
    'My Rating': 4,
    'Average Rating': 4.31,
    Publisher: 'Pocket Star Books',
    Binding: 'Paperback',
    'Number of Pages': 512,
    'Year Published': 2004,
    'Original Publication Year': 2003,
    'Date Read': '2018/12/22',
    'Date Added': '2018/12/05',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 9300768,
    Title: 'The Heroes (First Law World, #5)',
    Author: 'Joe Abercrombie',
    'Author l-f': 'Abercrombie, Joe',
    'Additional Authors': '',
    ISBN: '0316123358',
    ISBN13: 9780316123358,
    'My Rating': 4,
    'Average Rating': 4.31,
    Publisher: 'Orbit',
    Binding: 'ebook',
    'Number of Pages': 581,
    'Year Published': 2011,
    'Original Publication Year': 2011,
    'Date Read': '2018/12/05',
    'Date Added': '2018/11/07',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 149267,
    Title: 'The Stand',
    Author: 'Stephen King',
    'Author l-f': 'King, Stephen',
    'Additional Authors': 'Bernie Wrightson',
    ISBN: '0385199570',
    ISBN13: 9780385199575,
    'My Rating': 4,
    'Average Rating': 4.34,
    Publisher: 'Doubleday Books',
    Binding: 'Hardcover',
    'Number of Pages': 1152,
    'Year Published': 1990,
    'Original Publication Year': 1978,
    'Date Read': '2018/10/13',
    'Date Added': '2018/08/28',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 386372,
    Title: 'Mort (Discworld, #4; Death, #1)',
    Author: 'Terry Pratchett',
    'Author l-f': 'Pratchett, Terry',
    'Additional Authors': '',
    ISBN: '0061020680',
    ISBN13: 9780061020681,
    'My Rating': 5,
    'Average Rating': 4.23,
    Publisher: 'Harpertorch',
    Binding: 'Mass Market Paperback',
    'Number of Pages': 243,
    'Year Published': 2001,
    'Original Publication Year': 1987,
    'Date Read': '2018/08/25',
    'Date Added': '2018/08/17',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 417730,
    Title: 'Dreamsongs, Volume II',
    Author: 'George R.R. Martin',
    'Author l-f': 'Martin, George R.R.',
    'Additional Authors': 'Leslie Kay Swigart',
    ISBN: '0553806580',
    ISBN13: 9780553806588,
    'My Rating': 0,
    'Average Rating': 4.03,
    Publisher: 'Bantam Spectra',
    Binding: 'Hardcover',
    'Number of Pages': 740,
    'Year Published': 2007,
    'Original Publication Year': 2003,
    'Date Read': '',
    'Date Added': '2018/07/20',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 937249,
    Title: 'Separation of Power (Mitch Rapp, #5)',
    Author: 'Vince Flynn',
    'Author l-f': 'Flynn, Vince',
    'Additional Authors': '',
    ISBN: '0671047345',
    ISBN13: 9780671047344,
    'My Rating': 4,
    'Average Rating': 4.31,
    Publisher: 'Pocket Books',
    Binding: 'Paperback',
    'Number of Pages': 448,
    'Year Published': 2002,
    'Original Publication Year': 2001,
    'Date Read': '2018/06/17',
    'Date Added': '2018/06/06',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 2315892,
    Title: 'Best Served Cold',
    Author: 'Joe Abercrombie',
    'Author l-f': 'Abercrombie, Joe',
    'Additional Authors': '',
    ISBN: '0575082453',
    ISBN13: 9780575082458,
    'My Rating': 5,
    'Average Rating': 4.19,
    Publisher: 'Gollancz',
    Binding: 'Hardcover',
    'Number of Pages': 534,
    'Year Published': 2009,
    'Original Publication Year': 2009,
    'Date Read': '2018/06/06',
    'Date Added': '2018/05/10',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 22752699,
    Title: 'Seveneves',
    Author: 'Neal Stephenson',
    'Author l-f': 'Stephenson, Neal',
    'Additional Authors': '',
    ISBN: '0062190415',
    ISBN13: 9780062190413,
    'My Rating': 0,
    'Average Rating': 3.99,
    Publisher: 'William Morrow',
    Binding: 'ebook',
    'Number of Pages': 880,
    'Year Published': 2015,
    'Original Publication Year': 2015,
    'Date Read': '2018/03/12',
    'Date Added': '2018/02/15',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 944076,
    Title: 'Last Argument of Kings (The First Law, #3)',
    Author: 'Joe Abercrombie',
    'Author l-f': 'Abercrombie, Joe',
    'Additional Authors': '',
    ISBN: '0575077905',
    ISBN13: 9780575077904,
    'My Rating': 5,
    'Average Rating': 4.3,
    Publisher: 'Gollancz',
    Binding: 'Trade Paperback',
    'Number of Pages': 536,
    'Year Published': 2008,
    'Original Publication Year': 2008,
    'Date Read': '2018/02/04',
    'Date Added': '2018/01/09',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': 'Splendid!',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 32283133,
    Title: 'Origin (Robert Langdon, #5)',
    Author: 'Dan Brown',
    'Author l-f': 'Brown, Dan',
    'Additional Authors': '',
    ISBN: '0385514239',
    ISBN13: 9780385514231,
    'My Rating': 4,
    'Average Rating': 3.88,
    Publisher: 'Doubleday',
    Binding: 'Hardcover',
    'Number of Pages': 456,
    'Year Published': 2017,
    'Original Publication Year': 2017,
    'Date Read': '2017/12/25',
    'Date Added': '2017/12/04',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 944073,
    Title: 'The Blade Itself (The First Law, #1)',
    Author: 'Joe Abercrombie',
    'Author l-f': 'Abercrombie, Joe',
    'Additional Authors': '',
    ISBN: '0575079797',
    ISBN13: 9780575079793,
    'My Rating': 4,
    'Average Rating': 4.18,
    Publisher: 'Gollancz',
    Binding: 'Paperback',
    'Number of Pages': 515,
    'Year Published': 2007,
    'Original Publication Year': 2006,
    'Date Read': '2017/09/09',
    'Date Added': '2017/08/08',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 260025,
    Title: 'Test of the Twins (Dragonlance: Legends, #3)',
    Author: 'Margaret Weis',
    'Author l-f': 'Weis, Margaret',
    'Additional Authors': 'Tracy Hickman',
    ISBN: '0786933887',
    ISBN13: 9780786933884,
    'My Rating': 4,
    'Average Rating': 4.19,
    Publisher: 'Wizards of the Coast',
    Binding: 'Hardcover',
    'Number of Pages': 320,
    'Year Published': 2004,
    'Original Publication Year': 1986,
    'Date Read': '2017/06/14',
    'Date Added': '2017/05/27',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 23164927,
    Title: 'The Fold (Threshold, #2)',
    Author: 'Peter Clines',
    'Author l-f': 'Clines, Peter',
    'Additional Authors': '',
    ISBN: '0553418297',
    ISBN13: 9780553418293,
    'My Rating': 4,
    'Average Rating': 3.87,
    Publisher: 'Crown',
    Binding: 'Hardcover',
    'Number of Pages': 384,
    'Year Published': 2015,
    'Original Publication Year': 2015,
    'Date Read': '2017/05/06',
    'Date Added': '2017/04/17',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 93768,
    Title: 'War of the Twins (Dragonlance: Legends, #2)',
    Author: 'Margaret Weis',
    'Author l-f': 'Weis, Margaret',
    'Additional Authors': 'Tracy Hickman',
    ISBN: '0786932171',
    ISBN13: 9780786932177,
    'My Rating': 3,
    'Average Rating': 4.14,
    Publisher: 'Wizards of the Coast',
    Binding: 'Hardcover',
    'Number of Pages': 411,
    'Year Published': 2004,
    'Original Publication Year': 1986,
    'Date Read': '2016/10/22',
    'Date Added': '2016/08/30',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 12591698,
    Title: "Caliban's War (The Expanse, #2)",
    Author: 'James S.A. Corey',
    'Author l-f': 'Corey, James S.A.',
    'Additional Authors': '',
    ISBN: '1841499900',
    ISBN13: 9781841499901,
    'My Rating': 4,
    'Average Rating': 4.36,
    Publisher: 'Orbit',
    Binding: 'Paperback',
    'Number of Pages': 595,
    'Year Published': 2012,
    'Original Publication Year': 2012,
    'Date Read': '2016/08/30',
    'Date Added': '2016/07/21',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 29187,
    Title: 'Time of the Twins (Dragonlance: Legends, #1)',
    Author: 'Margaret Weis',
    'Author l-f': 'Weis, Margaret',
    'Additional Authors': 'Tracy Hickman',
    ISBN: '0786931582',
    ISBN13: 9780786931583,
    'My Rating': 3,
    'Average Rating': 4.16,
    Publisher: 'Wizards of the Coast',
    Binding: 'Kindle Edition',
    'Number of Pages': 389,
    'Year Published': 2004,
    'Original Publication Year': 1986,
    'Date Read': '2016/07/21',
    'Date Added': '2016/06/15',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 45244,
    Title: 'Judas Unchained (Commonwealth Saga, #2)',
    Author: 'Peter F. Hamilton',
    'Author l-f': 'Hamilton, Peter F.',
    'Additional Authors': 'Marta García Martínez',
    ISBN: '0345461665',
    ISBN13: 9780345461667,
    'My Rating': 4,
    'Average Rating': 4.3,
    Publisher: 'Del Rey Books',
    Binding: 'Hardcover',
    'Number of Pages': 827,
    'Year Published': 2006,
    'Original Publication Year': 2005,
    'Date Read': '2016/06/14',
    'Date Added': '2016/03/07',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 68378,
    Title: 'Dragons of Spring Dawning (Dragonlance: Chronicles, #3)',
    Author: 'Margaret Weis',
    'Author l-f': 'Weis, Margaret',
    'Additional Authors': 'Tracy Hickman',
    ISBN: '0786930705',
    ISBN13: 9780786930708,
    'My Rating': 4,
    'Average Rating': 4.11,
    Publisher: 'Wizards of the Coast',
    Binding: 'Hardcover',
    'Number of Pages': 352,
    'Year Published': 2003,
    'Original Publication Year': 1985,
    'Date Read': '2015/12/19',
    'Date Added': '2015/11/11',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 8855321,
    Title: 'Leviathan Wakes (The Expanse, #1)',
    Author: 'James S.A. Corey',
    'Author l-f': 'Corey, James S.A.',
    'Additional Authors': '',
    ISBN: '1841499889',
    ISBN13: 9781841499888,
    'My Rating': 5,
    'Average Rating': 4.27,
    Publisher: 'Orbit',
    Binding: 'Paperback',
    'Number of Pages': 561,
    'Year Published': 2011,
    'Original Publication Year': 2011,
    'Date Read': '2015/11/10',
    'Date Added': '2015/10/03',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 2913377,
    Title: 'The Name of the Wind (The Kingkiller Chronicle, #1)',
    Author: 'Patrick Rothfuss',
    'Author l-f': 'Rothfuss, Patrick',
    'Additional Authors': '',
    ISBN: '0575081406',
    ISBN13: 9780575081406,
    'My Rating': 4,
    'Average Rating': 4.52,
    Publisher: 'Gollancz',
    Binding: 'Paperback',
    'Number of Pages': 662,
    'Year Published': 2008,
    'Original Publication Year': 2007,
    'Date Read': '2013/05/11',
    'Date Added': '2013/03/31',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 603268,
    Title: 'Dragons of Winter Night (Dragonlance: Chronicles, #2)',
    Author: 'Margaret Weis',
    'Author l-f': 'Weis, Margaret',
    'Additional Authors': 'Tracy Hickman',
    ISBN: '0786916095',
    ISBN13: 9780786916092,
    'My Rating': 4,
    'Average Rating': 4.12,
    Publisher: 'Wizards of the Coast',
    Binding: 'Paperback',
    'Number of Pages': 395,
    'Year Published': 2000,
    'Original Publication Year': 1985,
    'Date Read': '2015/10/03',
    'Date Added': '2015/07/15',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 184655,
    Title: 'Transfer of Power (Mitch Rapp, #3)',
    Author: 'Vince Flynn',
    'Author l-f': 'Flynn, Vince',
    'Additional Authors': '',
    ISBN: '1416516352',
    ISBN13: 9781416516354,
    'My Rating': 4,
    'Average Rating': 4.32,
    Publisher: 'Pocket Books',
    Binding: 'Paperback',
    'Number of Pages': 549,
    'Year Published': 2005,
    'Original Publication Year': 1999,
    'Date Read': '2015/07/15',
    'Date Added': '2015/05/23',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 259836,
    Title: 'Dragons of Autumn Twilight  (Dragonlance: Chronicles, #1)',
    Author: 'Margaret Weis',
    'Author l-f': 'Weis, Margaret',
    'Additional Authors': 'Tracy Hickman',
    ISBN: '0786915749',
    ISBN13: 9780786915743,
    'My Rating': 3,
    'Average Rating': 4,
    Publisher: 'Wizards of the Coast',
    Binding: 'Mass Market Paperback',
    'Number of Pages': 444,
    'Year Published': 2000,
    'Original Publication Year': 1984,
    'Date Read': '2015/05/23',
    'Date Added': '2015/04/25',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 28691,
    Title: 'To Green Angel Tower (Memory, Sorrow, and Thorn, #3)',
    Author: 'Tad Williams',
    'Author l-f': 'Williams, Tad',
    'Additional Authors': '',
    ISBN: '0756402980',
    ISBN13: 9780756402983,
    'My Rating': 4,
    'Average Rating': 4.19,
    Publisher: 'DAW',
    Binding: 'Paperback',
    'Number of Pages': 1083,
    'Year Published': 2005,
    'Original Publication Year': 1993,
    'Date Read': '2015/03/24',
    'Date Added': '2014/09/30',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review':
      'A nice ending to the epic saga...but way too long. It took me almost 4 months to complete and the final of the book was somewhat anticlimactic. Still the journey was never boring and I already start to miss some characters since Tad Williams is a wonderful storyteller. No surprise G.R.R. Martin took this book as an inspiration to his A Song of Ice and Fire, though this series is not so dark and gruesome. All in all I recommended this book to fantasy-lovers, yet some plot points may seem seem a bit clichéd now.',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 55030,
    Title: 'Cosmos',
    Author: 'Carl Sagan',
    'Author l-f': 'Sagan, Carl',
    'Additional Authors': '',
    ISBN: '0375508325',
    ISBN13: 9780375508325,
    'My Rating': 5,
    'Average Rating': 4.38,
    Publisher: 'Random House',
    Binding: 'Mass Market Paperback',
    'Number of Pages': 365,
    'Year Published': 2002,
    'Original Publication Year': 1980,
    'Date Read': '',
    'Date Added': '2015/02/09',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 317449,
    Title: 'The Dragonbone Chair (Memory, Sorrow, and Thorn, #1)',
    Author: 'Tad Williams',
    'Author l-f': 'Williams, Tad',
    'Additional Authors': '',
    ISBN: '0886773849',
    ISBN13: 9780886773847,
    'My Rating': 4,
    'Average Rating': 3.95,
    Publisher: 'DAW Fantasy',
    Binding: 'Mass Market Paperback',
    'Number of Pages': 783,
    'Year Published': 1989,
    'Original Publication Year': 1988,
    'Date Read': '2014/07/20',
    'Date Added': '2014/05/13',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 529579,
    Title: 'The Next 100 Years: A Forecast for the 21st Century',
    Author: 'George Friedman',
    'Author l-f': 'Friedman, George',
    'Additional Authors': '',
    ISBN: '038551705X',
    ISBN13: 9780385517058,
    'My Rating': 4,
    'Average Rating': 3.67,
    Publisher: 'Doubleday',
    Binding: 'Hardcover',
    'Number of Pages': 272,
    'Year Published': 2009,
    'Original Publication Year': 2008,
    'Date Read': '2014/05/07',
    'Date Added': '2014/04/30',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 17212231,
    Title: 'Inferno (Robert Langdon, #4)',
    Author: 'Dan Brown',
    'Author l-f': 'Brown, Dan',
    'Additional Authors': '',
    ISBN: '0385537859',
    ISBN13: 9780385537858,
    'My Rating': 5,
    'Average Rating': 3.87,
    Publisher: 'Doubleday',
    Binding: 'Hardcover',
    'Number of Pages': 463,
    'Year Published': 2013,
    'Original Publication Year': 2013,
    'Date Read': '2014/04/26',
    'Date Added': '2014/04/11',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review':
      "At first I thought that Brown constructed his new novel from all his time-proven plot elements, e.g. female sidekick, solving riddles hidden into the art objects, dealing with secret societies and so on. But in the second half it  became evident that Brown managed to fool everyone and the finale is absolutely surprising. The book also has some deep insights on human overpopulation problem, bioengineering, evolution, and, of course,  some of author's favorite themes, like history and architecture – all in a guise of a fast-paced thriller. All in all, Inferno is much better reading than previous Robert Langdon novel, The Lost Symbol. Five out of  five on my scale, recommended for reading.",
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 13824169,
    Title: 'Wired (Wired, #1)',
    Author: 'Douglas E. Richards',
    'Author l-f': 'Richards, Douglas E.',
    'Additional Authors': '',
    ISBN: '0982618492',
    ISBN13: 9780982618493,
    'My Rating': 4,
    'Average Rating': 3.86,
    Publisher: 'Paragon Press',
    Binding: 'Paperback',
    'Number of Pages': 352,
    'Year Published': 2013,
    'Original Publication Year': 2005,
    'Date Read': '2013/07/18',
    'Date Added': '2013/07/01',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 10592,
    Title: 'Carrie',
    Author: 'Stephen King',
    'Author l-f': 'King, Stephen',
    'Additional Authors': 'Sissy Spacek',
    ISBN: '1416524304',
    ISBN13: 9781416524304,
    'My Rating': 4,
    'Average Rating': 3.98,
    Publisher: 'Pocket Books',
    Binding: 'Mass Market Paperback',
    'Number of Pages': 253,
    'Year Published': 2005,
    'Original Publication Year': 1974,
    'Date Read': '2013/12/18',
    'Date Added': '2013/12/12',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 6320534,
    Title: 'Under the Dome',
    Author: 'Stephen King',
    'Author l-f': 'King, Stephen',
    'Additional Authors': '',
    ISBN: '1439148503',
    ISBN13: 9781439148501,
    'My Rating': 4,
    'Average Rating': 3.91,
    Publisher: 'Scribner',
    Binding: 'Hardcover',
    'Number of Pages': 1074,
    'Year Published': 2009,
    'Original Publication Year': 2009,
    'Date Read': '2013/09/13',
    'Date Added': '2013/08/02',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review':
      'Not much of a horror novel, but still a book absolutely worth to read. "The fact is, we\'re all live under the dome" (c) The author',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 96472,
    Title: 'Sundiver (The Uplift Saga, #1)',
    Author: 'David Brin',
    'Author l-f': 'Brin, David',
    'Additional Authors': '',
    ISBN: '0553269828',
    ISBN13: 9780553269826,
    'My Rating': 3,
    'Average Rating': 3.69,
    Publisher: 'Bantam Spectra',
    Binding: 'Mass Market Paperback',
    'Number of Pages': 340,
    'Year Published': 2010,
    'Original Publication Year': 1980,
    'Date Read': '2013/08/02',
    'Date Added': '2013/07/20',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 6941985,
    Title: '1984',
    Author: 'George Orwell',
    'Author l-f': 'Orwell, George',
    'Additional Authors': '',
    ISBN: '0156035847',
    ISBN13: 9780156035842,
    'My Rating': 5,
    'Average Rating': 4.19,
    Publisher: 'Houghton Mifflin Harcourt (HMH)',
    Binding: 'ebook',
    'Number of Pages': 0,
    'Year Published': 2008,
    'Original Publication Year': 1949,
    'Date Read': '2013/07/01',
    'Date Added': '2013/06/14',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 17699389,
    Title: 'CyberStorm (CyberStorm #1)',
    Author: 'Matthew Mather',
    'Author l-f': 'Mather, Matthew',
    'Additional Authors': '',
    ISBN: '0991677196',
    ISBN13: 9780991677191,
    'My Rating': 5,
    'Average Rating': 3.79,
    Publisher: 'PhutureNews Publishing',
    Binding: 'Paperback',
    'Number of Pages': 364,
    'Year Published': 2013,
    'Original Publication Year': 2013,
    'Date Read': '2013/06/14',
    'Date Added': '2013/06/04',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review':
      "One of the very best technothrillers I've read to date. A pageturner, and a thought-provoking book too. Even strange that Amazon gives this title out with the price of just a buck. Five stars out of five, highly recommended for reading.",
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 9359796,
    Title: 'Vortex (Spin, #3)',
    Author: 'Robert Charles Wilson',
    'Author l-f': 'Wilson, Robert Charles',
    'Additional Authors': '',
    ISBN: '0765323427',
    ISBN13: 9780765323422,
    'My Rating': 4,
    'Average Rating': 3.75,
    Publisher: 'Tor Books',
    Binding: 'Hardcover',
    'Number of Pages': 331,
    'Year Published': 2011,
    'Original Publication Year': 2011,
    'Date Read': '2013/05/23',
    'Date Added': '2013/05/11',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 15796303,
    Title: '14 (Threshold, #1)',
    Author: 'Peter Clines',
    'Author l-f': 'Clines, Peter',
    'Additional Authors': '',
    ISBN: '1618680528',
    ISBN13: 9781618680525,
    'My Rating': 5,
    'Average Rating': 3.96,
    Publisher: 'Permuted Press',
    Binding: 'Paperback',
    'Number of Pages': 352,
    'Year Published': 2012,
    'Original Publication Year': 2012,
    'Date Read': '2013/03/22',
    'Date Added': '2013/03/10',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review':
      'An interesting blend of thriller, science fiction and everyday life.',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 481866,
    Title: 'Sea of Silver Light (Otherland, #4)',
    Author: 'Tad Williams',
    'Author l-f': 'Williams, Tad',
    'Additional Authors': '',
    ISBN: '0756400309',
    ISBN13: 9780756400309,
    'My Rating': 5,
    'Average Rating': 4.14,
    Publisher: 'DAW',
    Binding: 'Mass Market Paperback',
    'Number of Pages': 1066,
    'Year Published': 2002,
    'Original Publication Year': 2001,
    'Date Read': '2013/01/16',
    'Date Added': '2012/11/25',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review':
      'An epic finale to one of the best sci-fi series i have read to date',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 960,
    Title: 'Angels & Demons (Robert Langdon, #1)',
    Author: 'Dan Brown',
    'Author l-f': 'Brown, Dan',
    'Additional Authors': '',
    ISBN: '1416524797',
    ISBN13: 9781416524793,
    'My Rating': 5,
    'Average Rating': 3.92,
    Publisher: 'Pocket Books',
    Binding: 'Mass Market Paperback',
    'Number of Pages': 736,
    'Year Published': 2006,
    'Original Publication Year': 2000,
    'Date Read': '',
    'Date Added': '2012/11/25',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 10084,
    Title: 'River of Blue Fire (Otherland, #2)',
    Author: 'Tad Williams',
    'Author l-f': 'Williams, Tad',
    'Additional Authors': '',
    ISBN: '0886778441',
    ISBN13: 9780886778446,
    'My Rating': 4,
    'Average Rating': 4.03,
    Publisher: 'Daw Books',
    Binding: 'Mass Market Paperback',
    'Number of Pages': 675,
    'Year Published': 1999,
    'Original Publication Year': 1998,
    'Date Read': '',
    'Date Added': '2012/11/25',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 28695,
    Title: 'City of Golden Shadow (Otherland, #1)',
    Author: 'Tad Williams',
    'Author l-f': 'Williams, Tad',
    'Additional Authors': '',
    ISBN: '0886777631',
    ISBN13: 9780886777630,
    'My Rating': 4,
    'Average Rating': 3.92,
    Publisher: 'DAW Books',
    Binding: 'Mass Market Paperback',
    'Number of Pages': 780,
    'Year Published': 1998,
    'Original Publication Year': 1996,
    'Date Read': '',
    'Date Added': '2012/11/25',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 417729,
    Title: 'Dreamsongs, Volume I',
    Author: 'George R.R. Martin',
    'Author l-f': 'Martin, George R.R.',
    'Additional Authors': 'Gardner Dozois',
    ISBN: '0553805452',
    ISBN13: 9780553805451,
    'My Rating': 5,
    'Average Rating': 3.96,
    Publisher: 'Bantam Spectra',
    Binding: 'Hardcover',
    'Number of Pages': 683,
    'Year Published': 2007,
    'Original Publication Year': 2003,
    'Date Read': '',
    'Date Added': '2012/11/25',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 10090,
    Title: 'Mountain of Black Glass (Otherland, #3)',
    Author: 'Tad Williams',
    'Author l-f': 'Williams, Tad',
    'Additional Authors': '',
    ISBN: '0886779065',
    ISBN13: 9780886779061,
    'My Rating': 4,
    'Average Rating': 4.06,
    Publisher: 'Daw Books',
    Binding: 'Mass Market Paperback',
    'Number of Pages': 749,
    'Year Published': 2000,
    'Original Publication Year': 1999,
    'Date Read': '',
    'Date Added': '2012/11/25',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 55399,
    Title: 'Gardens of the Moon (Malazan Book of the Fallen, #1)',
    Author: 'Steven Erikson',
    'Author l-f': 'Erikson, Steven',
    'Additional Authors': '',
    ISBN: '0765348780',
    ISBN13: 9780765348784,
    'My Rating': 1,
    'Average Rating': 3.9,
    Publisher: 'Tor Books',
    Binding: 'Mass Market Paperback',
    'Number of Pages': 657,
    'Year Published': 2005,
    'Original Publication Year': 1999,
    'Date Read': '',
    'Date Added': '2012/11/25',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 10572,
    Title: 'A Clash of Kings  (A Song of Ice and Fire, #2)',
    Author: 'George R.R. Martin',
    'Author l-f': 'Martin, George R.R.',
    'Additional Authors': '',
    ISBN: '0553381695',
    ISBN13: 9780553381696,
    'My Rating': 5,
    'Average Rating': 4.41,
    Publisher: 'Bantam',
    Binding: 'Paperback',
    'Number of Pages': 969,
    'Year Published': 2002,
    'Original Publication Year': 1998,
    'Date Read': '',
    'Date Added': '2012/11/25',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 99219,
    Title: 'The Butlerian Jihad (Legends of Dune, #1)',
    Author: 'Brian Herbert',
    'Author l-f': 'Herbert, Brian',
    'Additional Authors': 'Kevin J. Anderson',
    ISBN: '0765340771',
    ISBN13: 9780765340771,
    'My Rating': 3,
    'Average Rating': 3.77,
    Publisher: 'Tor Books',
    Binding: 'Paperback',
    'Number of Pages': 684,
    'Year Published': 2003,
    'Original Publication Year': 2002,
    'Date Read': '',
    'Date Added': '2012/11/25',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 161296,
    Title: 'Schismatrix Plus',
    Author: 'Bruce Sterling',
    'Author l-f': 'Sterling, Bruce',
    'Additional Authors': '',
    ISBN: '0441003702',
    ISBN13: 9780441003709,
    'My Rating': 1,
    'Average Rating': 3.93,
    Publisher: 'Ace Books',
    Binding: 'Paperback',
    'Number of Pages': 336,
    'Year Published': 1996,
    'Original Publication Year': 1996,
    'Date Read': '',
    'Date Added': '2012/11/25',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 102439,
    Title: 'Rainbows End',
    Author: 'Vernor Vinge',
    'Author l-f': 'Vinge, Vernor',
    'Additional Authors': '',
    ISBN: '0812536363',
    ISBN13: 9780812536362,
    'My Rating': 2,
    'Average Rating': 3.77,
    Publisher: 'Tor Science Fiction',
    Binding: 'Paperback',
    'Number of Pages': 381,
    'Year Published': 2007,
    'Original Publication Year': 2006,
    'Date Read': '',
    'Date Added': '2012/11/25',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 62291,
    Title: 'A Storm of Swords (A Song of Ice and Fire, #3)',
    Author: 'George R.R. Martin',
    'Author l-f': 'Martin, George R.R.',
    'Additional Authors': '',
    ISBN: '055357342X',
    ISBN13: 9780553573428,
    'My Rating': 5,
    'Average Rating': 4.54,
    Publisher: 'Bantam',
    Binding: 'Mass Market Paperback',
    'Number of Pages': 1177,
    'Year Published': 2003,
    'Original Publication Year': 2000,
    'Date Read': '',
    'Date Added': '2012/11/25',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 13497,
    Title: 'A Feast for Crows (A Song of Ice and Fire, #4)',
    Author: 'George R.R. Martin',
    'Author l-f': 'Martin, George R.R.',
    'Additional Authors': '',
    ISBN: '055358202X',
    ISBN13: 9780553582024,
    'My Rating': 3,
    'Average Rating': 4.14,
    Publisher: 'Bantam Books',
    Binding: 'Mass Market Paperback',
    'Number of Pages': 1061,
    'Year Published': 2011,
    'Original Publication Year': 2005,
    'Date Read': '',
    'Date Added': '2012/11/25',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 3326157,
    Title: 'Axis (Spin, #2)',
    Author: 'Robert Charles Wilson',
    'Author l-f': 'Wilson, Robert Charles',
    'Additional Authors': '',
    ISBN: '0765348268',
    ISBN13: 9780765348265,
    'My Rating': 3,
    'Average Rating': 3.52,
    Publisher: 'Tor Science Fiction',
    Binding: 'Mass Market Paperback',
    'Number of Pages': 355,
    'Year Published': 2008,
    'Original Publication Year': 2007,
    'Date Read': '',
    'Date Added': '2012/11/25',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 910863,
    Title: 'Spin (Spin, #1)',
    Author: 'Robert Charles Wilson',
    'Author l-f': 'Wilson, Robert Charles',
    'Additional Authors': '',
    ISBN: '076534825X',
    ISBN13: 9780765348258,
    'My Rating': 4,
    'Average Rating': 4.02,
    Publisher: 'Tor Science Fiction',
    Binding: 'Mass Market Paperback',
    'Number of Pages': 464,
    'Year Published': 2006,
    'Original Publication Year': 2005,
    'Date Read': '',
    'Date Added': '2012/11/25',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 99220,
    Title: 'The Battle of Corrin (Legends of Dune, #3)',
    Author: 'Brian Herbert',
    'Author l-f': 'Herbert, Brian',
    'Additional Authors': 'Kevin J. Anderson',
    ISBN: '0765340798',
    ISBN13: 9780765340795,
    'My Rating': 3,
    'Average Rating': 3.76,
    Publisher: 'Tor Books',
    Binding: 'Mass Market Paperback',
    'Number of Pages': 704,
    'Year Published': 2005,
    'Original Publication Year': 2004,
    'Date Read': '',
    'Date Added': '2012/11/25',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 715060,
    Title:
      'Deadly Relations: Bester Ascendant (Babylon 5: Saga of Psi Corps, #2)',
    Author: 'Greg Keyes',
    'Author l-f': 'Keyes, Greg',
    'Additional Authors': '',
    ISBN: '0345427165',
    ISBN13: 9780345427168,
    'My Rating': 4,
    'Average Rating': 3.89,
    Publisher: 'Del Rey',
    Binding: 'Mass Market Paperback',
    'Number of Pages': 266,
    'Year Published': 1999,
    'Original Publication Year': 1999,
    'Date Read': '',
    'Date Added': '2012/11/25',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 99218,
    Title: 'The Machine Crusade (Legends of Dune, #2)',
    Author: 'Brian Herbert',
    'Author l-f': 'Herbert, Brian',
    'Additional Authors': 'Kevin J. Anderson',
    ISBN: '076534078X',
    ISBN13: 9780765340788,
    'My Rating': 3,
    'Average Rating': 3.77,
    Publisher: 'Tor',
    Binding: 'Mass Market Paperback',
    'Number of Pages': 800,
    'Year Published': 2004,
    'Original Publication Year': 2003,
    'Date Read': '',
    'Date Added': '2012/11/25',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 6250159,
    Title: 'Anathem',
    Author: 'Neal Stephenson',
    'Author l-f': 'Stephenson, Neal',
    'Additional Authors': '',
    ISBN: '006147410X',
    ISBN13: 9780061474101,
    'My Rating': 4,
    'Average Rating': 4.16,
    Publisher: 'Harper',
    Binding: 'Mass Market Paperback',
    'Number of Pages': 981,
    'Year Published': 2009,
    'Original Publication Year': 2008,
    'Date Read': '',
    'Date Added': '2012/11/25',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 8583760,
    Title: 'The Lost Symbol (Robert Langdon, #3)',
    Author: 'Dan Brown',
    'Author l-f': 'Brown, Dan',
    'Additional Authors': '',
    ISBN: '0552161233',
    ISBN13: 9780552161237,
    'My Rating': 3,
    'Average Rating': 3.73,
    Publisher: 'Corgi Books',
    Binding: 'Paperback',
    'Number of Pages': 670,
    'Year Published': 2010,
    'Original Publication Year': 2009,
    'Date Read': '',
    'Date Added': '2012/11/25',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 77251,
    Title:
      'Final Reckoning: The Fate of Bester (Babylon 5: Saga of Psi Corps, #3)',
    Author: 'Greg Keyes',
    'Author l-f': 'Keyes, Greg',
    'Additional Authors': 'J. Gregory Keyes, J. Michael Straczynski',
    ISBN: '0345427173',
    ISBN13: 9780345427175,
    'My Rating': 3,
    'Average Rating': 3.94,
    Publisher: 'Del Rey Books',
    Binding: 'Paperback',
    'Number of Pages': 272,
    'Year Published': 1999,
    'Original Publication Year': 1999,
    'Date Read': '',
    'Date Added': '2012/11/25',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 1111903,
    Title:
      'Dark Genesis: The Birth of the Psi Corps (Babylon 5: Saga of Psi Corps, #1)',
    Author: 'Greg Keyes',
    'Author l-f': 'Keyes, Greg',
    'Additional Authors': '',
    ISBN: '0345427157',
    ISBN13: 9780345427151,
    'My Rating': 3,
    'Average Rating': 3.85,
    Publisher: 'Del Rey',
    Binding: 'Paperback',
    'Number of Pages': 288,
    'Year Published': 1998,
    'Original Publication Year': 1998,
    'Date Read': '',
    'Date Added': '2012/11/25',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
  {
    'Book Id': 4703581,
    Title: 'The City & the City',
    Author: 'China Miéville',
    'Author l-f': 'Miéville, China',
    'Additional Authors': '',
    ISBN: '0345497511',
    ISBN13: 9780345497512,
    'My Rating': 4,
    'Average Rating': 3.9,
    Publisher: 'Del Rey/Ballantine Books',
    Binding: 'Hardcover',
    'Number of Pages': 312,
    'Year Published': 2009,
    'Original Publication Year': 2009,
    'Date Read': '',
    'Date Added': '2012/11/25',
    Bookshelves: '',
    'Bookshelves with positions': '',
    'Exclusive Shelf': 'read',
    'My Review': '',
    Spoiler: '',
    'Private Notes': '',
    'Read Count': 1,
    'Recommended For': '',
    'Recommended By': '',
    'Owned Copies': 0,
    'Original Purchase Date': '',
    'Original Purchase Location': '',
    Condition: '',
    'Condition Description': '',
    BCID: '',
  },
];

export default  exportedData;
